---
version: "3"
services:
  service1:
    container_name: cont1
    build: "./docker-app"
    ports:
      - "1111:8080"

  service2:
    container_name: cont2
    build: "./docker-db"
    ports:
      - "2222:3306"



...
